version: '3.8'

services:

  app:
    image: dmytroafro/current
    ports:
      - "443:443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/container_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  echem_db:
    driver: local