INSERT INTO products (opt_price,
                             price, id,
                             country_producer,
                             on_stock,
                             photo_url,
                             producer,
                             product_description,
                             title)
VALUES (null,
        235.00,
        nextval('product_seq'),
        null,
        'ON_STOCK',
        '/images/products/vitis/anticaries.jpeg',
        'VITIS',
        'Зубна паста VITIS ANTICARIES забезпечує ефективний захист від карієсу та кислотних ерозій, глибоко відновлює та зміцнює емаль завдяки інноваційній технології DENTAID haprepair. Рекомендується для комплексного догляду за зубами та яснами для людей всіх вікових груп починаючи з 7 років.',
        'VITIS ANTICARIES зубна паста 100 мл');


INSERT INTO products (opt_price,
                      price, id,
                      country_producer,
                      on_stock,
                      photo_url,
                      producer,
                      product_description,
                      title)
VALUES (null,
        230.00,
        nextval('product_seq'),
        null,
        'ON_STOCK',
        '/images/products/vitis/sensitive.jpeg',
        'VITIS',
        'Зубна паста VITIS SENSITIVE призначена для профілактики і зняття чутливості зубів. В основі VITIS SENSITIVE лежить технологія DENTAID haprepair, яка вже з першого застосування пасти сприяє природному відновленню емалі та формуванню захисного шару. Швидко усуває чутливість зубів.',
        'VITIS SENSITIVE зубна паста 100 мл');

INSERT INTO products (opt_price,
                      price, id,
                      country_producer,
                      on_stock,
                      photo_url,
                      producer,
                      product_description,
                      title)
VALUES (null,
        260.00,
        nextval('product_seq'),
        null,
        'ON_STOCK',
        '/images/products/vitis/whitening.jpeg',
        'VITIS',
        'VITIS WHITENING (ВІТІС ВАЙТЕНІН) – зубна паста для білосніжної усмішки! Має низьку абразивність, не ушкоджує емаль і не викликає чутливість. Видаляє плями від кави та чаю. Містить активний гідроксиапатит, який сприяє відновленню зубної емалі. Допомагає зберегти білизну зубів після відбілювання. Рекомендується для щоденного використання.',
        'VITIS WHITENING зубна паста 100 мл');