spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/shop
    username: admin
    password: 9921
  flyway:
    baseline-on-migrate: true