server:
  port: 8080
  host: http://localhost:8080/
#  port: 443
#  host: https://185.69.153.13/
  error:
    include-message: always
    include-binding-errors: always
#  ssl:
#    key-store: file:/etc/letsencrypt/live/e-chem.com.ua/keystore.p12
#    key-store-password: ${KEY_PASS}
#    key-alias: tomcat
#    key-store-type: PKCS12

spring:
  application:
    name: internet-shop
  output:
    ansi:
      enabled: detect
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgresDialect
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/database_ec
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  mail:
    host: mail.adm.tools
    port: 2525
    username: control@e-chem.com.ua
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 2000
          writetimeout: 5000

currency:
  url: https://v6.exchangerate-api.com/v6/${C_TOKEN}/latest/