spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eeeee
    username: postgres
    password: 5876
  flyway:
    baseline-on-migrate: true
