spring:
  #  це я для методу PATCH включив
  mvc:
    hiddenmethod:
      filter:
        enabled: true
# ----------------
  application:
    name: internet-shop
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgresDialect
      hibernate:
        format_sql: false
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  mail:
    host: mail.e-chem.com.ua
    port: 587
    username: confirmation-email@e-chem.com.ua
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 2000
          writetimeout: 5000
  groovy:
    template:
      cache: false

currency:
  url: https://v6.exchangerate-api.com/v6/${C_TOKEN}/latest/