server:
  port: 8083
  host: http://localhost:8083/

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: internet-shop-local
  datasource:
    url: jdbc:postgresql://localhost:5432/ec
#    url: jdbc:postgresql://host.docker.internal:5432/database_ec