spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


  datasource:
    url: jdbc:postgresql://localhost:5432/s1
    username: postgres
    password: 5876
  flyway:
    baseline-on-migrate: true



logging:
  file.name: logs/appLog.log
  pattern:
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%t] %clr(%-5level) %logger{36} - %msg%n"
  level:
    root: INFO